### PR TITLE
Support AnnotatedSection@description as a JSX Element

### PR DESCRIPTION
**Pull request by exchange321**
**The following MUST be checked prior to approval. If not relevant to your PR, remove the line from your description.**
- [x]  The `styleguide.config.js` has been updated to show examples/new functionality for the component
- [ ]  Test Coverage for any new or updated functionality
- [x]  New and updated components have been tested locally in lapis and SPA and work as expected
- [x]  This PR has been tagged with PATCH, MINOR, or MAJOR.
- [ ]  The component has data-component-type and data-component-context attributes following the standard
- [x]  You have requested a cross-team review on this component so everyone knows it exists

### CODE REVIEW

**Comment by MichaelDevenish** [comment]
this is against the original definition of the annotated section, whats the reason for this change?

**Comment by exchange321** [comment]
@MichaelDevenish To fulfil the design requirements from the designers. The `header` already accepts JSX.Element, why can't `description` accept JSX.Element too?

**Comment by exchange321** [comment]
Basically the design requirement is having a line break between two sentences and have one term in those sentences in bold. @MichaelDevenish Is there an alternative way to achieve this requirement?

**Comment by MichaelDevenish** [comment]
hmm i dont fully agree to the header being able to have jsx passed. what does the design look like?

**Comment by MichaelDevenish** [comment]
do you have a screenshot of the design?

**Comment by exchange321** [comment]
@MichaelDevenish https://github.com/intellihr/ui-components/blob/develop/src/domain/Layouts/SectionList/subcomponents/AnnotatedSection.tsx#L14

We don't have a mockup, it's just an enhancement to what we currently have:
image

**Comment by exchange321** [comment]
`header` as a JSX Element is also present in the example, so I assume it's agreed by team phi and the design team?

**Comment by MichaelDevenish** [comment]
I was on leave when the pr was made to change that so i don't beleive it was a decision that was discussed with the team. don't know how it could be done but i feel like this solution could be abused to do unintended behaviour.

**Comment by MichaelDevenish** [comment]
i'd honestly have a prop to override it and allow jsx but the default prop is enforced to be a string

**Pull request closed without merging**
